import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./Features/components/Navbar";
import Footer from "./Features/components/Footer";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Dil foods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <div className=" lg:container lg:mx-auto md:px-40 overflow-hidden relative">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
